name: CraftklinikLife
main: CraftklinikLife\CraftklinikLife
api: [3.1.1]
version: 1.0.0
author: Craftklinik

commands:
 test:
  description: "Use Life Command"
  permission: use.life

heal:
  description: "Heal yourself"
  permission: life.heal

food:
  description: "Feed yourself"
  permission: life.food
